### ISSUE TITLE
Android 13 completely broke this app

### ISSUE THREAD

**Issue by candroid-man** [NeoApplications/Neo-Launcher#238]
When you try to open any app the launcher crashes.

**Comment by saulhdev** [comment]
are you able to get the crash log and share it?

**Comment by candroid-man** [comment]
Where do I find that?

**Comment by machiav3lli** [comment]
If you have root access then you can use Scoop (from F-Droid), otherwise you'll have to use a logcat app using adb e.g. Matlog.

Just to put this in context, other users on Telegram reported the app is working just fine on A13, so maybe you gotta maybe do some debugging on your side to discover what may cause this. Is there anything special about your setup?

**Comment by candroid-man** [comment]
Hi, I found the problem. For whatever reason I was running version: 0.9.0-beta2 (Build 920 ) which I guess is the debug version. I am in the process of switching to stable now, but I suppose it is good for you to know that debug version is broken unless you already knew. Anyways sorry about the confusion, I will go ahead and close this out
