### ISSUE TITLE
Malware warning popping up

### ISSUE THREAD

**Issue by VHUGO98** [NeoApplications/Neo-Launcher#296]
## Description
 A warning keeps popping up saying that the launcher is potential malware, false positive but I don't know what is triggering the warning.

## Expected Behavior
 That the system does not consider the app to be malware

## Actual Behavior
 The system warns of the potential danger and does not allow to install

## Steps to Reproduce
 I just tried to install the app

## Device and OS

* Device: Motorola Moto G9 Plus 
* Android version: 11
* Launcher version: 0.9.3
* Rom: Stock Motorola

## Logcat

```

```

**Comment by machiav3lli** [comment]
Does this apply only to 0.9.3? And did you check the SHA256 of the downloaded apk? If so, it could be that there's a specific sequence of bits that matches a malware pattern (this is how modern AV work), so it's possibly a one-in-(more-than-)million chance or it could be that because we don't have a Google developer accounts and it compares that.
